### PR TITLE
Create EU localisation

### PR DESCRIPTION
**Pull request by xabirequejo**
Initial localisation.

### CODE REVIEW

**Comment by mczachurski** [comment]
Can you translate also that file: `Vernissage/PixelfedKit/Sources/PixelfedKit/Resources/en.lproj/Localizable.strings`?

**Comment by xabirequejo** [comment]
Sure

**Comment by mczachurski** [comment]
Thank you. When I will add new set of titles I will add them in English to eu files also, so time to time it wold be great if you will fix them 😉.

**Comment by xabirequejo** [comment]
Awesome! I'll keep an eye on the files to keep them up to date and improve the initial translation.

**Comment by mczachurski** [comment]
Great, thank you! I added two new lines before you did a merge: 
"settings.title.rate" = "Rate Vernissage";
"settings.title.socials" = "Socials";

**Pull request merged**
